name: Build and Test React Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install front dependencies
        working-directory: ./my-app
        run: npm ci

      - name: Run unit tests with coverage
        working-directory: ./my-app
        run: npm test -- --coverage
        env:
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}

      - name: Build the stack with Docker
        run: |
          docker compose --version
          docker compose up -d
        env:
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}

      - name: Wait for frontend to be ready
        working-directory: ./my-app
        run: npx wait-on http://localhost:3000

      - name: Run e2e tests with Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./my-app

      - name: Stop the stack
        run: docker compose down

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./my-app/coverage/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: alucrece/Deploiement_continu

      - name: Build React app
        working-directory: ./my-app
        run: npm run build --if-present
        env:
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}