name: Build and Test React Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and run frontend tests
        working-directory: ./my-app
        run: |
          npm ci
          npm test -- --coverage
        env:
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}

      - name: Create .env file for backend
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" > ./server/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> ./server/.env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> ./server/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> ./server/.env
          # Ajoute d'autres variables si besoin ici

      - name: Build the stack (docker)
        run: |
          docker compose --version
          docker compose up -d
        env:
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}

      - name: Stop the stack (docker)
        run: docker compose down
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./my-app/coverage/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: alucrece/Deploiement_continu

      #- name: Run e2e tests with Cypress
       # uses: cypress-io/github-action@v6
       # with:
        #  working-directory: ./my-app

      - name: Build and generate docs
        working-directory: ./my-app
        run: |
          npm run jsdoc
          npm run build --if-present
        env:
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
      
      - name: Configure Git identity
        working-directory: ./my-app
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Deploy to GitHub Pages
        working-directory: ./my-app
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install backend dependencies and run backend tests
        working-directory: ./server
        run: |
          npm ci
      
      - name: Deploy backend to Vercel
        run: npx vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
        working-directory: ./server